#!/usr/bin/env bash

ROOT_PATH=$(cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && cd .. && pwd)

export SCP_MACHINE_PATH="${SCP_MACHINE_PATH:-${ROOT_PATH}}"
export SCP_MACHINE_CMAKE_PATH="${SCP_MACHINE_CMAKE_PATH:-${SCP_MACHINE_PATH}}"
export SCP_MACHINE_CXX_SOURCES_PATH="${SCP_MACHINE_CXX_SOURCES_PATH:-${SCP_MACHINE_PATH}/scp}"
export SCP_MACHINE_BUILD_PATH="${SCP_MACHINE_BUILD_PATH:-${SCP_MACHINE_CMAKE_PATH}/build}"
export BINARY_PATH="${BINARY_PATH:-${SCP_MACHINE_CMAKE_PATH}/bin}"
